project:
  type: book
  output-dir: docs

book:
  title: "Estadística a Inferencia II"
  author:
    - name: Osvaldo A. Martin 
      url: https://aloctavodia.github.io/
      affiliation: IMASL-CONICET
      affiliation-url: https://gmp.net.ar
      orcid: 0000-0001-7419-8978
      address: Italia 1556
      city: San Luis
      state: San Luis
      country: Argentina
      postal-code: 5700
  date: today
  chapters:
    - index.qmd
    - 01_Inferencia_Bayesiana.ipynb
    - 02_Programación_probabilística.ipynb
    - 03_Modelos_jerárquicos.ipynb

  page-navigation: true
  reader-mode: true
  page-footer: <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Licencia Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/80x15.png" /></a><br />Este obra está bajo <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">licencia Creative Commons Reconocimiento 4.0 Internacional</a>.
  sidebar:
    style: "docked"
    search: true
    tools:
      - icon: github
        text: github
        menu:
          - text: Fuente
            url:  https://github.com/LCD-UNSAM/estadistica_e_inferencia_II
          - text: Reportar errores
            url:  https://github.com/LCD-UNSAM/estadistica_e_inferencia_II/issues/new


format:
  html:
    toc: true
    code-line-numbers: true
    code-summary: "Mostrar Código"
    number-sections: true
    number-offset: -1
    lang: es
    language: 
      title-block-author-single: "Autor"
      title-block-published: "Última modificación"
      toggle-dark-mode: "Modo claro/oscuro"
      toggle-reader-mode: "Modo sin distracciones"
      search: "Buscar"
    

theme:
  light: cosmo
  dark: darkly

